version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: cargo
    rebase-strategy: auto
    schedule:
      timezone: "Europe/London"
      interval: monthly
      time: "04:00"
